
- name: Initialize config replicaset
  include_tasks: "config.yml"
  vars:
    replica_set: "cfg"

- name: Initialize data replicasets
  include_tasks: "replicaset.yml"
  vars:
    replica_set: "{{ item }}"
  loop: "{{ replica_sets }}"

- name: Initialize shards
  include_tasks: "shards.yml"
