
- include_role:
     name: community.mongodb.mongodb_repository
  when: inventory_hostname in groups['rs0']

- include_role:
     name: community.mongodb.mongodb_mongod
  vars:
     sharding: true
  when: inventory_hostname in groups['rs0']

- name: Install the OS packages
  ansible.builtin.apt:
    name:
      - python-setuptools
      - python3
      - python3-pip
      - mongodb-org-shell
    state: present
    update_cache: yes
  when: inventory_hostname == groups['rs0'][0]

- name: Install pymongo as dependency for some modules
  ansible.builtin.pip:
    name:
      - pymongo
    state: present
    executable: pip3
  when: inventory_hostname == groups['rs0'][0]

- name: Initialise MongoDB Replicaset rs0
  community.mongodb.mongodb_replicaset:
    login_database: "admin"
    login_host: localhost
    login_port: "27017"
    replica_set: "rs0"
    members:
      - "server4.unixway.org:27017"
      - "server5.unixway.org:27017"
      - "server6.unixway.org:27017"
  when: inventory_hostname == groups['rs0'][0]
  register: config_status

- name: Printing status
  ansible.builtin.debug:
    var: config_status
  when: inventory_hostname == groups['rs0'][0]

- name: Ensure replicaset has reached a converged state
  community.mongodb.mongodb_status:
    replica_set: "rs0"
    login_database: "admin"
    login_host: localhost
    login_port: "27017"
    poll: 10
    interval: 10
  when: config_status.changed == True
