
- name: Simple playbook
  gather_facts: true
  hosts: all
  serial: 10
  remote_user: root

  tasks:
     - name: Simple ping
       ansible.builtin.ping:

     - name: Simple shell
       ansible.builtin.shell: hostname && w
       register: result

     - name: Print execution result
       ansible.builtin.debug:
         var: result
