---
# Names on replicasets as they defined in inventory file
replica_sets: []

# Information about port conentions
# https://docs.mongodb.com/manual/reference/default-mongodb-port/
mongos_service_port: "27017"
mongod_data_port: "27018"
mongod_config_port: "27019"

# Default admin password set up for accessing mongodb with mongos
# Change it to something random
mongo_admin_password: "admin"

# All communication between mongodb nodes should use
# internal interface on the nodes and not using public internet facing routes
private_interface: 'eth0'
