
- name: Playbook for Common Initialization
  gather_facts: true
  hosts: all
  serial: 10
  remote_user: root

  tasks:
     - name: Install the OS packages in Debian
       ansible.builtin.apt:
         name:
           - vim
         state: present
         update_cache: yes
       when: ansible_facts['os_family'] == "Debian"

     - name: Install the OS packages in CentOS
       ansible.builtin.yum:
         name:
           - vim
         state: present
       when: ansible_facts['os_family'] == "CentOS"
