
 - name: Install packages dependencies
   include_tasks: "packages.yml"

 - name: Get service code
   include_tasks: "service.yml"

 - name: Install and configure uwsgi
   include_tasks: "uwsgi.yml"

 - name: Install and configure nginx
   include_tasks: "nginx.yml"

 - name: Restart services if required
   meta: flush_handlers

 - name: Test service health check
   include_tasks: "test.yml"
