 - name: Install the OS packages
   ansible.builtin.apt:
     name:
       - python-setuptools
       - nginx
       - git
       - python3
       - python3-pip
     state: present
     update_cache: yes
